port: 8317
auth-dir: /tmp/cpa-pool/auths
debug: false
logging-to-file: true
usage-statistics-enabled: true
remote-management:
  allow-remote: true
  secret-key: ""
  disable-control-panel: false
  disable-auto-update-panel: false
